### ISSUE TITLE
Trouble with donut / multipart polygons

### ISSUE THREAD

**Issue by jGaboardi** [ljwolf/cenpy#14]
@ljwolf  have found some strangeness concerning overlapping census blocks (and only blocks, not tracts or block groups). [This example gist](https://gist.github.com/jGaboardi/bbeee8de72dc401d16ea867b5fe4cd99) shows one example of an overlapping case when using cenpy.  The same census blocks are not overlapping when the data is downloaded from the census website. This appears to be an issue with the parsing of interior coords for donuts and secondary parts for multipart polygons.

Using:
* cenpy 0.8.8.0dev
* python 2.7.13

**Comment by ljwolf** [comment]
Yep, this is definitely an issue. I, a fool, initially underestimated the complexity of moving from the ESRI polygon to the OGC polygon :upside_down_face: Sorry about this & thanks for finding it. 

In full, the issue was twofold. First, the software has an index error, cutting too far into the polygon object. So, for polygons with holes, you lose the hole. 

More generally, a correct mapping from the census API to  shapely requires mapping the ESRI arrays of directed rings to the OGC nested tuples of rings. This is pretty routine, but there's an ambiguity with how multipart polygons with holes are defined. I've tried to resolve this ambiguity by always creating an OGC shape, but sometimes creating an invalid OGC shape. To fix this, you'd have to check which exterior ring owns which interior ring, which could be slow for large datasets or detailed polygons, both of which cenpy deals with.

**Comment by ljwolf** [comment]
From new current master:
![2017-10-25-000758_1000x532_scrot](https://user-images.githubusercontent.com/2250995/31972485-eab19fb8-b918-11e7-89f4-f26843f1010d.png)

**Comment by ljwolf** [comment]
From new current master:
![2017-10-25-000945_1002x1034_scrot](https://user-images.githubusercontent.com/2250995/31972510-02be3652-b919-11e7-9a82-62f943dda9a1.png)

**Comment by ljwolf** [comment]
to backport this to previous cenpy versions, you only need to bring along [this commit.](https://github.com/ljwolf/cenpy/commit/47a5514ec87609fbdad8d327f1f5cb5e086de8ff).

**Comment by ljwolf** [comment]
To close this ticket:

[ ] test Polygons, multipolygons, polygons with holes, and well-formatted multipolygons with holes. 
[ ] test multipoints

**Comment by jGaboardi** [comment]
[Your fix](https://github.com/ljwolf/cenpy/commit/47a5514ec87609fbdad8d327f1f5cb5e086de8ff) works for me on python 2.7.13!

**Comment by ljwolf** [comment]
Resolved.
