### ISSUE TITLE
Python 3.4.2 support

### ISSUE THREAD

**Issue by geoffrey-eisenbarth** [ljwolf/cenpy#20]
Would you be interested in a pull-request that supports Python 3.4 imports? Since 3.4 is the latest version available in the Debian repository, it seems like this might be a desired feature.

I haven't tried out all the features, yet, but I was able to import cenpy with only five one-line changes to the imports.

Edit: BTW, love this library: thanks so much for all your work! It demystifies a lot of the issues I've had with their API and trying to find out how to build the right URL queries!

**Comment by ljwolf** [comment]
Huh... you're definitely correct. Sorry about that :slightly_frowning_face: 

My commit's definitely in error; I should've forced greater than 3.5 to keep install consistent with testing, so I'll take a PR to fix it to raise the `setup.py` `install_requires>=3.5` if you've got the time to submit it. 

I'd like to not remove the `JSONDecodeError` import & I intend to build future code on top of 3.5. (anyone in the spatialucr set have a take on that? Not sure if this is too constraining for OSLNAP @sjsrey @knaaptime @suhanmappingideas).

I'd intended to target 3.5 because it's what's in [Debian stretch](https://wiki.debian.org/Python#Supported_Python_Versions3), which is what I thought was the current stable Debian version?

**Comment by geoffrey-eisenbarth** [comment]
I'll submit the PR for ``setup.py`` shortly.

My understanding is that it's not uncommon to try/except various imports to support multiple versions of Python, but obviously you and those mentioned have more of a feel for whether or not you should support Python 3.4. I didn't realize it was in Debian Stretch; I've been using Jessie since it was the default on my VPS (DigitalOcean). It's been awhile since I've looked into dist-upgrade, I should do that! :)

**Comment by sjsrey** [comment]
I don't foresee any constraints for OSLNAP with going 3.5 as we are in early days there and should be building on 3.4+. Thanks for checking!

**Comment by ljwolf** [comment]
cenpy `0.9.8` is up on pypi with this fix merged. I just checked that I cannot install it in python 3.4:

```
$> conda create -n cenpytest python=3.4 
$> source activate cenpytest
$> pip install --no-cache-dir cenpy
```
gives me the right install crash when running with python 3.4.5.
