### ISSUE TITLE
TIGER Line roads with cenpy?

### ISSUE THREAD

**Issue by jGaboardi** [ljwolf/cenpy#22]
Levi,

I have been trying (with no luck) to use cenpy (with python 2.7 out of neccesity unfortunately) to grab all roads within a specified county from 2010 [All Roads-->State-->County]. It is super easy to do over with the [web interface](https://www.census.gov/cgi-bin/geo/shapefiles/index.php?year=2010&layergroup=Roads), but would love to incorporate more of cenpy into my workflow for automation.

I spoke with @dfolch about it earlier today and he thought that I might not be possible with cenpy because there is no demographic data included with the roads.

What do you think about this? If it is possible (and easy to do), would you mind putting up an example?

- James

**Comment by ljwolf** [comment]
Hey,

No, that's not currently supported, but it's not because of presence/lack of demographic data. Making it work wouldn't be too difficult, and I can get you close.

This is done in `tiger.py`, which right now points directly to all the [tigerweb services](https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb). This is set by [`cenpy.tiger._baseurl`](https://github.com/ljwolf/cenpy/blob/master/cenpy/tiger.py#L14) directly in the code. 

But, this is only [one of the possible services in the list of ESRI services](https://tigerweb.geo.census.gov/arcgis/rest/services). You can just as easily change that `_baseurl` to Basemap (where the roads are), and the auto-wrapping stuff in cenpy will try to expose that just like it does TIGERweb. When I do that locally:

```py
import cenpy as cp
cp.tiger._baseurl = "https://tigerweb.geo.census.gov/arcgis/rest/services/Basemaps"
cp.tiger._basequery = {} # to turn off the templating I do specific to TIGERweb
```
I then can connect to the basemap stuff just like the other service:
```py
cxn = t2.TigerConnection('CommunityTIGER')
```
And the road layers are layers 6-8. 

So you can definitely query them straight from that. 

But, I don't see them having "state" or "county" fields, and I don't know what their variable schema means. You can look that up on the [html interface to the ESRI server](https://tigerweb.geo.census.gov/arcgis/rest/services/Basemaps/CommunityTIGER/MapServer/6). I can get a basic test query to make a connection & grab data:

```
primary_roads = cxn.layer[6]
primary_roads.query(where='STGEOMETRY.LEN > 0', **{"ResultRecordCount":5})
```
but I haven't written a `polyline` parser in `cenpy.geoparser`.
If that's written (which probably can adapt what's in there), it'll work. 

To fully implement the feature:
1. check `https://tigerweb.geo.census.gov/arcgis/rest/services` for all relevant mapservices
2. Let `TigerConnection` override the default service `TIGERWeb` with others
3. Write/adapt code for an `esriGeometryPolyline` parser.

**Comment by jGaboardi** [comment]
@ljwolf super answer! I haven't had the time implement this yet, but it looks promising.

**Comment by ljwolf** [comment]
I tried to keep it all as general as possible so it'd be easy to extend :smile: 

Would love to help where I can. I think the polyline parser should be as easy as repeated applications of the line parser...

**Comment by jGaboardi** [comment]
Maybe we can get together for a hack at AAG? I'll be there Monday evening through Sunday morning.

**Comment by ljwolf** [comment]
Huh, so this way you're pulling from the http-interface of the ftp, getting the zipfiles, dumping to disk, and then reading them again? 

It would be very easy to adapt what you've done into a url generator focused on www2.census.gov. I didn't think we were supposed to hit that ftp programmatically, which is why I built around the geo API `https://tigerweb.geo.census.gov/arcgis/rest/services`... admittedly I don't like dealing with that API. 

@loganpowell might have advice here, but I don't think I documented why I thought the "right" one to hit up for the geometries was the arcgis rest api...

**Comment by loganpowell** [comment]
Sorry for the delayed response. I have a horrible issues backlog...

The FTP will allow you to get way more data in a single payload than the tigerweb API. While we do recommend using the API we wouldn't say not to hit the FTP programmatically.

Btw, is that a jupyter notebook in github?

**Comment by ljwolf** [comment]
Thanks @loganpowell for the clarification, & yep jupyter notebooks render by default in repositories & gists! it's pretty sweet :smile: 

OK, then @jGaboardi we can build this however you like. I really don't like using/building on top of the tigerweb API...
