### ISSUE TITLE
Instead of throwing the 400 error generically, provide the census API output and document the URL behavior

### ISSUE THREAD

**Issue by ljwolf** [ljwolf/cenpy#33]
Right now, any time there's an error in the way the query is constructed, we're throwing generic `400` errors and providing the exact query url. 

It might be more helpful if I customized these errors to get the actual text from the census API. This would mean that you'd get the "real" reason the error is thrown according to the census, rather than the generic HTTP status code, which is always 400 when an invalid query is run. 

This would let users (like Yoonjung, who emailed @ljwolf about a 400 error relating to [this query](https://api.census.gov/data/timeseries/qwi/sa?get=EmpSpv,Emp,EmpTotal,EmpEnd,EmpS,industry&for=county:*&in=state:12&year=2017&quarter=3&sex=0)) see the error locally, and avoid incentivising going *out of* the notebook to open the website.

**Comment by dfolch** [comment]
+1 on this. I was "sure" that my failed query was due to picking the wrong database. Turns out that in 2017 `GEOID` is `GEO_ID`. Manually pasting the [failed query](https://api.census.gov/data/2017/acs/acs5?get=B01003_001E,B01003_001M,B11016_001E,B11016_001M,B19025_001E,B19025_001M,NAME,GEOID&for=tract&in=state:12+county:095) into a web browser revealed my mistake.

Since the code already returns the failed URI, maybe a quick solution is to add some text to the output advising the user to paste the URI into a web browser to get details on the source of the failure. It didn't occur to me to do this until reading this issue.

**Comment by ljwolf** [comment]
Thanks for this bump. Looked into this back on a trans-atlantic plane in December & fixed it, but couldn't test it. 

Pushed into #35, but will need to test.

**Comment by ljwolf** [comment]
resolved by #35
